date: last-modified
execute:
  warning: false
message: false
format:
  html:
    code-fold: true
    link-external-icon: true
    link-external-newwindow: true
embed-resources: true
toc: true
title-block-banner: "#1D886E"
css: style.css
project:
  title: ""
  output-dir: results/quarto_output/
